<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{b98af3ec-355a-4bfd-b73e-6129ab2fe437}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a,b,c,d:int;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[c:=a+b;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>